
### Users ###

POST http://0.0.0.0:5000/signup
Content-Type: application/json

{
    "username": "admin",
    "email": "admin@gmail.com",
    "password": "admin",
    "isAdin": true
}


###


POST http://0.0.0.0:5000/login
Content-Type: application/json

{
    "email": "admin@gmail.com",
    "password": "admin"
}

###


GET http://0.0.0.0:5000/home
Authorization: Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpZCI6ImNmMDYyNmJmLTcxMTgtNGViNC04NjdjLWJlY2E3MThkM2U1NyIsInVzZXJuYW1lIjoiYWRtaW4iLCJjcmVhdGVkQXQiOiIyMDIxLTEwLTA4VDA3OjA5OjAxLjIyNFoiLCJpYXQiOjE2MzM3OTc4NDQsImV4cCI6MTYzMzc5Nzg2NH0.zGhXxazOKXbFCwJRfdGaMUk008OR1_OVHh_4jZxGymk

###

POST http://0.0.0.0:5000/token
Content-Type: application/json

{
    "refreshToken": "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpZCI6ImNmMDYyNmJmLTcxMTgtNGViNC04NjdjLWJlY2E3MThkM2U1NyIsInVzZXJuYW1lIjoiYWRtaW4iLCJwaWN0dXJlIjoiaHR0cHM6Ly9iaXQubHkvMld1b0JVUyIsImlzQWRtaW4iOmZhbHNlLCJjcmVhdGVkQXQiOiIyMDIxLTEwLTA4VDA3OjA5OjAxLjIyNFoiLCJpYXQiOjE2MzM3MDIxNDF9.DuFrXiWg_QZHsucjEsYlUYZcY71t8a5JUKmL9ZUzeiU"
}

### Resident ###


GET http://0.0.0.0:5000/resident?id=55dbae92-f210-4ceb-9226-64b0b83d22d7


###


POST http://0.0.0.0:5000/resident/add
Content-Type: application/json

{
    "familyId": "124",
    "nik": "124",
    "name": "MUHAIMIN",
    "place_dateOfBirth": "SERANG, 28-02-1995",
    "gender": "L",
    "bloodType": "AB",
    "rt": "009",
    "rw": "003",
    "maritalStatus": "BELUM KAWIN",
    "profession": "BELUM/TIDAK BEKERJA"
}


###


PUT http://0.0.0.0:5000/resident/edit?id=55dbae92-f210-4ceb-9226-64b0b83d22d7
Content-Type: application/json

{
    "nik": "0001"
}
